export const SETALLUSERS = 'SETALLUSERS';
export const LOADUSERS = 'LOADUSERS';
export const GETUSERSERROR = 'GETUSERSERROR';

export const LOADRESPONSIBILITY = " LOADRESPONSIBILITY";
export const GETRESPONSIBILITYERROR = "GETRESPONSIBILITYERROR";
export const SETALLRESPONSIBILITY = "SETALLRESPONSIBILITY";
export const UPDATERESPONSIBILITYARRAY = "UPDATERESPONSIBILITYARRAY";

export const CHANGEDEPORTMENTVISIBILITYSTATUS = "CHANGEDEPORTMENTVISIBILITYSTATUS";
export const CHANGERESPONSIBILITYSECIONVISIBILITY = "CHANGERESPONSIBILITYSECIONVISIBILITY";

export const ADDRESPONSIBILITYLINE = "ADDRESPONSIBILITYLINE";